name: GET images

on:
  #schedule:
    #- cron: "0 13 * * 1"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update Images
        run: |
          rm -r Images
          git config --global user.email "pcaladomoura@gmail.com"
          git config --global user.name "Pedro Calado Moura"
          git submodule add https://.:${{ secrets.CLONE_TOKEN }}@github.com/cat-milk/Anime-Girls-Holding-Programming-Books.git
          mv Anime-Girls-Holding-Programming-Books Images
          git add .
          git commit -m "Automatic publish from github.com/project"
          git push https://github.com/feijoes/AnimeGirls-with-Books-API.git master
          echo Update
